# Generated by Django 5.2.3 on 2025-06-27 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(help_text='Brief title for the main task.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the main task.', max_length=15)),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=1, help_text='Priority level (e.g., 1=High, 2=Medium, 3=Low).')),
                ('due_date', models.DateTimeField(blank=True, help_text='Due date for the task.', null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['due_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title for the sub-task.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the sub-task.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the sub-task.', max_length=15)),
                ('due_date', models.DateTimeField(blank=True, help_text='Due date for the sub-task.', null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_sub_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_sub_tasks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='The main task this sub-task belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Sub-Task',
                'verbose_name_plural': 'Sub-Tasks',
                'ordering': ['due_date', 'task__priority'],
            },
        ),
    ]
